# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelli < Formula
  desc "Persistent interactive shell sessions via PTY"
  homepage "https://github.com/schovi/shelli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schovi/shelli/releases/download/v0.1.0/shelli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1677876db6307b4fa705cfde89649e18083562987bc9e81827055001b79b8126"

      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schovi/shelli/releases/download/v0.1.0/shelli_0.1.0_darwin_arm64.tar.gz"
      sha256 "c9b030e5cc108ac4a55cce90612c47204869dfeb11c8e978a7e99900407e240b"

      def install
        bin.install "shelli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.1.0/shelli_0.1.0_linux_amd64.tar.gz"
      sha256 "a0602600a7f9849835b57dcdba6c99664b38175273b45928e3dccadd3309c34f"
      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.1.0/shelli_0.1.0_linux_arm64.tar.gz"
      sha256 "8f146addfd49c54a91cd01d0316ac7571c7dcbfe80c680fc0486e6918bd08738"
      def install
        bin.install "shelli"
      end
    end
  end
end
