# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-treehouse" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "212c4f3075f1327036c12e8fb853263f9ec80b2988dd3635362bb5bbeee2a9e4"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a87bbe65c52f2f17d39ac1dd07e37729b9c35c198047af8dde4f44ae91522ba5"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9438aa89312701734eaab36ed658d7eccbb22fc73e22976247f41332eb1ce412"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "14bd0078b0268fcda27fab9d4144858c4d77cd7bae6218923308d46fe1d2ee32"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-treehouse"
  desc "TUI for managing Git worktrees"
  homepage "https://github.com/schovi/git-treehouse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-treehouse"
  binary "gth"

  # No zap stanza required

end
