# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-treehouse" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8d36d3b0f5cc4cbe71d8468e195eb44b008759215a6f80cec3753839595b6274"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b36a673dc4d926307c820cfa89eb09d870cd665d7dd4e1048e2002609444a9b7"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3cebbd1a7116c6e43702c3ba7373619a99b676a9e7df580a30da3fe9b1d9ce9"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bec26a40f8743074b98edc6a59bf53c7bb581e2aa891f64a581ddb00b57db66"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-treehouse"
  desc "TUI for managing Git worktrees"
  homepage "https://github.com/schovi/git-treehouse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-treehouse"
  binary "gth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-treehouse"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gth"]
    end
  end

  # No zap stanza required

end
