# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-treehouse" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "2a7f498b82aa81f7e912ba6e48c769508f1c3dce8245fbff2b64e452581ea595"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b98f1ccd18e66ce1afa234970380bea83286f4cb731e36da817a7f32a92b1f2a"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "314203b9d80f150167d4d5479a08f8257a6879e0d837a60e7c8bc249022160f9"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0840732267f0c8bdedbcb13a930e5645c88cbb0aeb65b9a7096131c2ca00e487"
      url "https://github.com/schovi/git-treehouse/releases/download/v#{version}/git-treehouse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-treehouse"
  desc "TUI for managing Git worktrees"
  homepage "https://github.com/schovi/git-treehouse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-treehouse"
  binary "gth"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-treehouse"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gth"]
    end
  end

  # No zap stanza required

end
