# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelli < Formula
  desc "Persistent interactive shell sessions via PTY"
  homepage "https://github.com/schovi/shelli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schovi/shelli/releases/download/v1.1.0/shelli_1.1.0_darwin_amd64.tar.gz"
      sha256 "aaa36703751749374b7bd0ff5450b88021a89016ed4fb1c38eeeb9fff589b0a6"

      define_method(:install) do
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schovi/shelli/releases/download/v1.1.0/shelli_1.1.0_darwin_arm64.tar.gz"
      sha256 "22f08ceeb57b9ce3d135e1fc591caeea0827ccce4ed6a2623369f21ea7bfb5e7"

      define_method(:install) do
        bin.install "shelli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v1.1.0/shelli_1.1.0_linux_amd64.tar.gz"
      sha256 "49a8beebbb162d8af13108a532474368c727db4447326e2bf5865a45d34a8e11"
      define_method(:install) do
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v1.1.0/shelli_1.1.0_linux_arm64.tar.gz"
      sha256 "baf3ab154cb24c50c2a186a3213a034aa336e76a8fabbc17449e3102271b631b"
      define_method(:install) do
        bin.install "shelli"
      end
    end
  end
end
