# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelli < Formula
  desc "Persistent interactive shell sessions via PTY"
  homepage "https://github.com/schovi/shelli"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schovi/shelli/releases/download/v0.5.0/shelli_0.5.0_darwin_amd64.tar.gz"
      sha256 "27cc2df93446ef6f25c5d70dce5442305fd6385a3ceb68bda5722a444fe59db2"

      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schovi/shelli/releases/download/v0.5.0/shelli_0.5.0_darwin_arm64.tar.gz"
      sha256 "76ecee0b32e14abbf9c766abefb65bcba0d6136413ae3666b5d449a2e17ee8f1"

      def install
        bin.install "shelli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.5.0/shelli_0.5.0_linux_amd64.tar.gz"
      sha256 "be8df98c5fae1da44d01eeffad471fb36cf47232e37bd12ae6d7b3a5e412ae5d"
      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.5.0/shelli_0.5.0_linux_arm64.tar.gz"
      sha256 "91ab212e4a8372f1cba44424adc0c029021637ecd80854f6b2f150c29016d448"
      def install
        bin.install "shelli"
      end
    end
  end
end
