# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelli < Formula
  desc "Persistent interactive shell sessions via PTY"
  homepage "https://github.com/schovi/shelli"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schovi/shelli/releases/download/v0.9.0/shelli_0.9.0_darwin_amd64.tar.gz"
      sha256 "35887d346fd5d461c7475c4933da8348e5a31ffd8171743e6ba6689ab7e9f3c4"

      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schovi/shelli/releases/download/v0.9.0/shelli_0.9.0_darwin_arm64.tar.gz"
      sha256 "1c293b3d361784688984f8e55b81da6e825ccb67b53adc2683c88ddd846702c3"

      def install
        bin.install "shelli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.9.0/shelli_0.9.0_linux_amd64.tar.gz"
      sha256 "81db910e206fe0c86771014c37b5089a5b01d9406feecaa666ab23fdeee9a79e"
      def install
        bin.install "shelli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schovi/shelli/releases/download/v0.9.0/shelli_0.9.0_linux_arm64.tar.gz"
      sha256 "f70c7a317e0a411b6cb1b316555086a80db5399ba91d947058553cc1fcde234a"
      def install
        bin.install "shelli"
      end
    end
  end
end
